# FOR DEVELOPMENT

version: "3"
services:
    db:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123456
          MYSQL_DATABASE: bank_db
        ports:
        - 3308:3306 # avoid conflict with local machine database
        volumes:
        - internet_banking_db:/var/lib/mysql
    redis:
        image: redis:alpine
        ports:
        - 6380:6379

volumes:
    internet_banking_db:
