version: "3"
services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: bank_db
        ports:
            - 5432:5432
        volumes:
            - bank_db:/var/lib/postgresql/data
    adminer:
        image: adminer
        ports:
            - 8080:8080

volumes:
    bank_db:
