server:
    port: 8000
spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:bank_db}
        username: ${DB_USER:admin}
        password: ${DB_PASS:123456}
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri:
    data:
        rest:
            basePath: /api

springdoc:
    api-docs:
        path: /api-docs.json
    swagger-ui:
        path: /api-docs
