version: "2.1"
executors:
    node:
        docker:
            - image: node:13-alpine

commands:
    checkout_and_attach_workspace:
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: ls -al

jobs:
    install:
        executor: node
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-deps-{{ checksum "yarn.lock" }}
                    - v1-deps
            - run: yarn
            - save_cache:
                key: v1-deps-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
                    - node_modules
                    - packages/client/node_modules/
                    - packages/server/node_modules/
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
                      - packages/client/node_modules/
                      - packages/server/node_modules/
    test_client:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run: cd packages/client
            - run: yarn test --coverage
    test_server:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run: cd packages/server
            - run: yarn test:cov
    build_client:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run: cd packages/client
            - run: yarn build
    build_server:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run: cd packages/server
            - run: yarn build

workflows:
    main:
        jobs:
            - install
            - test_client:
                  requires:
                      - install
            - test_server:
                  requires:
                      - install
            - build_client:
                  requires:
                      - install
                      - test_client
            - build_server:
                  requires:
                      - install
                      - test_server
