version: "2.1"
executors:
    node:
        docker:
            - image: node:13-alpine

jobs:
    install:
        executor: node
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-deps-{{ checksum "yarn.lock" }}
                    - v1-deps
            - run: yarn
            - save_cache:
                key: v1-deps-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
                    - node_modules
                    - packages/client/node_modules/
                    - packages/server/node_modules/
    test_client:
        executor: node
        working_directory: ~/project/packages/client
        steps:
            - checkout
            - run: yarn test --coverage
    test_server:
        executor: node
        working_directory: ~/project/packages/server
        steps:
            - checkout
            - run: yarn test
    build_client:
        executor: node
        working_directory: ~/project/packages/client
        steps:
            - checkout
            - run: yarn build
    build_server:
        executor: node
        working_directory: ~/project/packages/server
        steps:
            - checkout
            - run: yarn build

workflows:
    main:
        jobs:
            - install
            - test_client:
                  requires:
                      - install
            - test_server:
                  requires:
                      - install
            - build_client:
                  requires:
                      - install
                      - test_client
            - build_server:
                  requires:
                      - install
                      - test_server
